import streamlit as st
import pandas as pd
import numpy as np
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go

st.set_page_config(
    page_title="EV-Scope | AI Social Listening",
    page_icon="🚗",
    layout="wide",
    initial_sidebar_state="expanded"
)

BASE = Path(__file__).resolve().parent
OUT = BASE / "outputs"

@st.cache_data
def load_csv(name):
    p = OUT / name
    if not p.exists():
        return pd.DataFrame()
    return pd.read_csv(p, low_memory=False)

tesla = load_csv("tesla_analyzed.csv")
youtube = load_csv("youtube_analyzed.csv")
models = load_csv("model_results.csv")
crisis = load_csv("crisis_events.csv")
influencers = load_csv("gephi/tesla_influencers.csv")
topics = load_csv("lda_topic_keywords.csv")
ai = load_csv("ai_enriched.csv")

st.sidebar.title("🚗 EV-Scope")
st.sidebar.caption("AI-Powered Social Listening Dashboard")

if tesla.empty:
    st.error("tesla_analyzed.csv is missing. Run the Python pipeline first.")
    st.stop()

# Normalize useful columns.
for c in ["engagement", "purchase_intent_flag", "vader_score"]:
    if c in tesla.columns:
        tesla[c] = pd.to_numeric(tesla[c], errors="coerce").fillna(0)

if "date_parsed" in tesla.columns:
    tesla["date_parsed"] = pd.to_datetime(tesla["date_parsed"], errors="coerce")

# Sentiment column generated by the current pipeline is `model_sentiment`.
# Keep fallbacks so the dashboard also works with older output files.
if "model_sentiment" in tesla.columns:
    sentiment_col = "model_sentiment"
elif "predicted_sentiment" in tesla.columns:
    sentiment_col = "predicted_sentiment"
elif "vader_sentiment" in tesla.columns:
    sentiment_col = "vader_sentiment"
else:
    sentiment_col = None

# Filters
st.sidebar.subheader("Filters")
if "language" in tesla.columns:
    langs = sorted(tesla["language"].dropna().astype(str).unique().tolist())
    selected_lang = st.sidebar.multiselect(
        "Language",
        langs,
        default=["en"] if "en" in langs else []
    )
    if selected_lang:
        tesla_f = tesla[tesla["language"].astype(str).isin(selected_lang)].copy()
    else:
        tesla_f = tesla.copy()
else:
    tesla_f = tesla.copy()

if "topic" in tesla_f.columns:
    topic_options = sorted(tesla_f["topic"].dropna().astype(str).unique())
    selected_topics = st.sidebar.multiselect("Topic", topic_options)
    if selected_topics:
        tesla_f = tesla_f[tesla_f["topic"].astype(str).isin(selected_topics)]

st.title("EV-Scope")
st.markdown("### AI-Powered Social Listening & Consumer Intelligence for Electric Vehicles")
st.caption("Tesla Twitter + EV YouTube + Sentiment140 benchmark | Streamlit dashboard")

# KPIs
total = len(tesla_f)
positive = int((tesla_f[sentiment_col] == "positive").sum()) if sentiment_col else 0
negative = int((tesla_f[sentiment_col] == "negative").sum()) if sentiment_col else 0
positive_pct = positive / total * 100 if total else 0
negative_pct = negative / total * 100 if total else 0
purchase = tesla_f["purchase_intent_flag"].mean() * 100 if "purchase_intent_flag" in tesla_f.columns and total else 0
avg_eng = tesla_f["engagement"].mean() if total else 0

c1,c2,c3,c4,c5 = st.columns(5)
c1.metric("Total Mentions", f"{total:,}")
c2.metric("Positive", f"{positive_pct:.1f}%")
c3.metric("Negative", f"{negative_pct:.1f}%")
c4.metric("Purchase Intent", f"{purchase:.1f}%")
c5.metric("Avg Engagement", f"{avg_eng:,.1f}")

st.divider()

tab1, tab2, tab3, tab4, tab5 = st.tabs([
    "📊 Executive Overview",
    "🗣 Consumer Voice",
    "📈 Trends",
    "👥 Influencers",
    "🤖 AI Action Center"
])

with tab1:
    col1,col2 = st.columns(2)

    with col1:
        if sentiment_col:
            s = tesla_f[sentiment_col].value_counts().reset_index()
            s.columns = ["sentiment","count"]
            fig = px.pie(s, names="sentiment", values="count", title="Sentiment Distribution")
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        if "topic" in tesla_f.columns:
            t = tesla_f["topic"].value_counts().reset_index()
            t.columns = ["topic","mentions"]
            fig = px.bar(t.head(10), x="mentions", y="topic", orientation="h",
                         title="Top Discussion Topics")
            st.plotly_chart(fig, use_container_width=True)

    if "topic" in tesla_f.columns and sentiment_col:
        x = tesla_f.groupby(["topic",sentiment_col]).size().reset_index(name="mentions")
        fig = px.bar(x, x="topic", y="mentions", color=sentiment_col,
                     barmode="group", title="Sentiment by Topic")
        st.plotly_chart(fig, use_container_width=True)

with tab2:
    col1,col2 = st.columns(2)

    with col1:
        if "intent" in tesla_f.columns:
            i = tesla_f["intent"].value_counts().reset_index()
            i.columns = ["intent","count"]
            fig = px.bar(i, x="intent", y="count", title="Consumer Intent")
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        if "topic" in tesla_f.columns:
            e = tesla_f.groupby("topic", as_index=False)["engagement"].mean()
            e = e.sort_values("engagement", ascending=False).head(10)
            fig = px.bar(e, x="topic", y="engagement",
                         title="Average Engagement by Topic")
            st.plotly_chart(fig, use_container_width=True)

    if not ai.empty and "emotion" in ai.columns:
        em = ai["emotion"].value_counts().reset_index()
        em.columns = ["emotion","count"]
        fig = px.bar(em, x="emotion", y="count", title="AI Emotion Analysis")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("Run ai_enrichment.py to populate the emotion analysis.")

with tab3:
    st.subheader("Social Media Trends")

    if "date_parsed" in tesla_f.columns:
        trend_df = tesla_f.copy()
        trend_df["date_parsed"] = pd.to_datetime(trend_df["date_parsed"], errors="coerce")
        trend_df = trend_df.dropna(subset=["date_parsed"])

        if trend_df.empty:
            st.info("No valid dates are available for the selected filters.")
        else:
            # The Tesla dataset is concentrated on a single calendar day.
            # Therefore use hourly aggregation instead of a misleading daily chart.
            unique_days = trend_df["date_parsed"].dt.date.nunique()

            if unique_days <= 1:
                trend_df["period"] = trend_df["date_parsed"].dt.floor("h")
                period_label = "Hour"
                title_suffix = "Hourly"
            else:
                trend_df["period"] = trend_df["date_parsed"].dt.floor("D")
                period_label = "Day"
                title_suffix = "Daily"

            d = trend_df.groupby("period").agg(
                mentions=("id", "count"),
                engagement=("engagement", "sum")
            ).reset_index()

            if sentiment_col:
                trend_df["negative_flag"] = (
                    trend_df[sentiment_col].astype(str).str.lower() == "negative"
                ).astype(int)
                neg = trend_df.groupby("period")["negative_flag"].mean().reset_index(
                    name="negative_rate"
                )
                d = d.merge(neg, on="period", how="left")

            col1, col2 = st.columns(2)

            with col1:
                fig = px.line(
                    d,
                    x="period",
                    y="mentions",
                    markers=True,
                    title=f"{title_suffix} Social Mentions",
                    labels={"period": period_label, "mentions": "Mentions"}
                )
                fig.update_xaxes(tickformat="%d %b %H:%M" if unique_days <= 1 else "%d %b")
                st.plotly_chart(fig, use_container_width=True)

            with col2:
                if "negative_rate" in d.columns:
                    fig = px.line(
                        d,
                        x="period",
                        y="negative_rate",
                        markers=True,
                        title=f"{title_suffix} Negative Sentiment Rate",
                        labels={"period": period_label, "negative_rate": "Negative Rate"}
                    )
                    fig.update_yaxes(tickformat=".0%")
                    fig.update_xaxes(tickformat="%H:%M" if unique_days <= 1 else "%d %b")
                    st.plotly_chart(fig, use_container_width=True)

            fig = px.bar(
                d,
                x="period",
                y="engagement",
                title=f"{title_suffix} Engagement",
                labels={"period": period_label, "engagement": "Total Engagement"}
            )
            fig.update_xaxes(tickformat="%H:%M" if unique_days <= 1 else "%d %b")
            st.plotly_chart(fig, use_container_width=True)

            if unique_days <= 1:
                st.info(
                    "The available Tesla dataset covers one calendar day, so the dashboard "
                    "uses hourly trends. This is more informative than displaying a one-point daily trend."
                )

    else:
        st.warning("Date field not available.")

    if not crisis.empty:
        crisis2 = crisis.copy()
        if "day" in crisis2.columns:
            crisis2["day"] = pd.to_datetime(crisis2["day"], errors="coerce")
            crisis2 = crisis2.dropna(subset=["day"])
            if len(crisis2) > 1:
                fig = px.line(
                    crisis2,
                    x="day",
                    y="crisis_score",
                    markers=True,
                    title="AI Early-Warning Crisis Score"
                )
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.info(
                    "Crisis trend needs multiple calendar periods. "
                    "With this dataset's single-day coverage, use the hourly social trends above."
                )

with tab4:
    st.subheader("Tesla Social Network")
    st.write("Network generated from username → reply_to interactions in the Tesla dataset.")

    if not influencers.empty:
        st.dataframe(
            influencers.head(20),
            use_container_width=True,
            hide_index=True
        )
        score_col = "InfluenceScore" if "InfluenceScore" in influencers.columns else None
        if score_col:
            top = influencers.head(15).sort_values(score_col)
            fig = px.bar(top, x=score_col, y="Id", orientation="h",
                         title="Top Network-Centrality-Based Accounts")
            st.plotly_chart(fig, use_container_width=True)

    st.info("Open outputs/gephi/tesla_network.gexf in Gephi for the full network visualization and community detection.")

with tab5:
    st.subheader("AI Action Center")

    if not crisis.empty:
        latest = crisis.iloc[-1]
        level = str(latest.get("crisis_level","low"))
        score = float(latest.get("crisis_score",0))
        st.metric("Current Screening Level", level.upper(), f"{score:.1f}/100")

        if level == "high":
            st.error("HIGH-RISK SOCIAL SIGNAL — human review required.")
        elif level == "medium":
            st.warning("MEDIUM-RISK SOCIAL SIGNAL — monitor and investigate.")
        else:
            st.success("LOW-RISK SOCIAL SIGNAL — continue monitoring.")

    st.markdown("#### Recommended AI decision logic")
    st.code("""
Social signal
     ↓
Sentiment + Topic + Intent
     ↓
Engagement
     ↓
Crisis screening
     ↓
n8n AI Agent
     ↓
Executive summary
     ↓
Recommended business action
     ↓
Human approval
""")

    st.markdown("#### Responsible AI rule")
    st.write(
        "AI outputs are decision-support signals. They must not be treated as proof of product defects, "
        "customer characteristics, fraud or a real-world crisis without human validation."
    )

st.sidebar.divider()
st.sidebar.markdown("**Project:** EV-Scope")
st.sidebar.markdown("**Data:** 3 datasets")
st.sidebar.markdown("**Automation:** n8n")
st.sidebar.markdown("**Dashboard:** Streamlit")
